"""Configuration management and logging setup.

Provides :class:`SystemConfig` for JSON/YAML-backed settings with environment
variable overrides and named profiles, plus :func:`setup_logging` for the
application-wide logging configuration.
"""

from __future__ import annotations

import json
import logging
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional


class SystemConfig:
	"""JSON/YAML-backed configuration with env var overrides and profiles.

	Settings are organised into logical sections: ``cache``, ``performance``,
	``sources``, ``security``, ``ui``, ``export``, ``notifications``. When a
	config file exists it is deep-merged onto the defaults so new keys added
	in future versions are automatically present.
	"""

	def __init__(self, profile_name: Optional[str] = None) -> None:
		self.config_dir = Path.home() / '.system_update'
		self.profiles_dir = self.config_dir / 'profiles'
		self.current_profile = profile_name

		self.config_dir.mkdir(exist_ok=True)
		self.profiles_dir.mkdir(exist_ok=True)

		self._update_paths(profile_name)

		self.settings = self._get_default_settings()
		# Seed a fresh profile with a default config so the dir isn't empty
		# (and the banner can show the file). Has to happen BEFORE load() so
		# the loader picks it up. No-op if config_file already exists.
		if profile_name and not self.config_file.exists():
			try:
				self.save()
			except Exception as e:
				logging.warning(f'Failed to seed profile {profile_name!r}: {e}')
		self.load()

	@staticmethod
	def _get_default_settings() -> Dict:
		"""Return the default settings dictionary."""
		return {
			'version': 1,
			'log_level': 'WARNING',
			'exclude': [],
			'cache': {
				'duration_hours': 2,
				'enabled': True,
				'incremental_enabled': True,
				'delta_enabled': True,
				'lru_max_items': 512,
				'prefetch_enabled': False,
				'prefetch_threshold_minutes': 15,
				'prune_after_days': 14,
				'storage_fields': [
					'name',
					'source',
					'version',
					'latestVersion',
					'appId',
					'status',
					'scanTime',
					'errorMsg',
					'installPath',
					'securityFindings',
				],
				'omit_empty_fields': True,
			},
			'performance': {
				'parallel_scan': True,
				'max_workers': 6,
				'timeout_seconds': 45,
			},
			'network': {
				'enabled': True,
				'cache_enabled': True,
				'cache_ttl_seconds': 3600,
				'rate_limit_seconds': 0.2,
				'timeout_seconds': 10,
			},
			'sources': {
				'winget': True,
				'chocolatey': True,
				'npm': True,
				'pnpm': True,
				'pip': True,
				'bun': True,
				'yarn': True,
				'path': True,
				'registry': True,
				'rust': True,
				'scoop': True,
				'dotnet': True,
				'appx': True,
				'msix': True,
				'drivers': True,
				'services': True,
				'psmodules': True,
				'vsextensions': True,
			},
			'security': {
				'enabled': True,
				'auto_check': True,
				'severity_threshold': 'medium',
			},
			'ui': {
				'theme': 'default',
				'show_stats': True,
				'compact_view': False,
				'color_scheme': 'vibrant',
				'display_format': 'auto',
			},
			'export': {
				'default_format': 'json',
				'include_timestamp': True,
			},
			'report': {
				'template_path': '',
				'logo_path': '',
				'branding': {
					'title': 'System Update Report',
					'subtitle': '',
					'company_name': '',
					'primary_color': '#0066cc',
					'accent_color': '#333333',
					'background_color': '#f5f5f5',
					'footer_text': 'Generated by System Update CLI',
				},
			},
			'notifications': {
				'notify_on_updates': True,
				'notify_on_scan_complete': False,
				'system_notifications': False,
				'email_enabled': False,
				'email_to': '',
				'smtp_server': '',
				'smtp_port': 587,
				'smtp_username': '',
				'smtp_password': '',
				'webhook_enabled': False,
				'webhook_url': '',
				'webhook_headers': {},
				# Hardening 1.3.2 — by default refuse webhook URLs that
				# resolve to private (RFC1918), loopback, link-local, or
				# unique-local IP ranges. Set to true only for self-hosted
				# ChatOps endpoints reachable inside the same network.
				'allow_private_hosts': False,
				'custom_script_enabled': False,
				'custom_script_path': '',
			},
			# Hardening 1.2.1 — Plugin loading is **off by default**. Plugins
			# under ``~/.system_update/plugins/`` execute arbitrary Python at
			# scan time, so the user must opt in. When enabled, the loader
			# rejects world-writable directories and (optionally) enforces a
			# SHA-256 allowlist at ``allowed.sha256``.
			'plugins': {
				'enabled': False,
				'paths': [],
				'require_hash_allowlist': False,
			},
		}

	def _update_paths(self, profile_name: Optional[str]) -> None:
		"""Update file paths based on the current profile."""
		if profile_name:
			profile_dir = self.profiles_dir / profile_name
			profile_dir.mkdir(exist_ok=True)
			base = profile_dir
		else:
			base = self.config_dir

		self.config_file = base / 'config.json'
		self.yaml_config_file = base / 'config.yaml'
		self.yml_config_file = base / 'config.yml'
		self.cache_file = base / 'cache.json'
		self.log_file = base / 'system.log'

	def reinit(self, profile_name: Optional[str]) -> None:
		"""Switch to a different profile and reload configuration.

		Auto-seeds a default ``config.json`` when activating a fresh profile
		so the profile directory isn't empty after first use.
		"""
		self.current_profile = profile_name
		self._update_paths(profile_name)
		self.settings = self._get_default_settings()
		if profile_name and not self.config_file.exists():
			try:
				self.save()
			except Exception as e:
				logging.warning(f'Failed to seed profile {profile_name!r}: {e}')
		self.load()

	def export_profile(self, output_path: str) -> bool:
		"""Export current profile settings to a JSON file."""
		try:
			export_data = {
				'profile_name': self.current_profile or 'default',
				'settings': self.settings,
				'exported_at': datetime.now().isoformat(),
			}
			with open(output_path, 'w', encoding='utf-8') as f:
				json.dump(export_data, f, indent=2)
			return True
		except Exception as e:
			logging.error(f'Failed to export profile: {e}')
			return False

	def import_profile(self, input_path: str, profile_name: Optional[str] = None) -> bool:
		"""Import settings from a profile JSON file."""
		try:
			with open(input_path, 'r', encoding='utf-8') as f:
				import_data = json.load(f)

			settings = import_data.get('settings')
			if not settings:
				logging.error('Invalid profile file: missing settings')
				return False

			target_profile = profile_name or import_data.get('profile_name', 'imported')
			self.reinit(target_profile)
			self.settings = settings
			self.save()
			return True
		except Exception as e:
			logging.error(f'Failed to import profile: {e}')
			return False

	def load(self) -> None:
		"""Load configuration from YAML or JSON, then apply env var overrides."""
		loaded_settings = self._read_config_file()

		if loaded_settings and isinstance(loaded_settings, dict):
			loaded_settings = self._migrate_config(loaded_settings)
			self._apply_smart_sources_filtering(loaded_settings)
			self._merge_settings(self.settings, loaded_settings)

		self._load_env_vars()
		self._validate_config()

	def _read_config_file(self) -> Optional[Dict]:
		"""Attempt to read settings from YAML (preferred) or JSON on disk."""
		yaml_path = (
			self.yaml_config_file
			if self.yaml_config_file.exists()
			else (self.yml_config_file if self.yml_config_file.exists() else None)
		)

		if yaml_path:
			try:
				import yaml

				with open(yaml_path, 'r', encoding='utf-8') as f:
					return yaml.safe_load(f)
			except ImportError:
				logging.warning('PyYAML not installed but YAML config found.')
			except Exception as e:
				logging.warning(f'Failed to load YAML config: {e}')

		if self.config_file.exists():
			try:
				with open(self.config_file, 'r', encoding='utf-8') as f:
					return json.load(f)
			except Exception as e:
				logging.warning(f'Failed to load config: {e}')

		return None

	def _apply_smart_sources_filtering(self, loaded_settings: Dict) -> None:
		"""Honour explicit user source choices: enabling any disables unlisted ones.

		If the user explicitly enables at least one source in the config file,
		every source not listed by the user gets disabled. This makes config
		files where the user lists only the sources they want act as a whitelist.
		"""
		if 'sources' not in loaded_settings or not isinstance(loaded_settings['sources'], dict):
			return

		user_sources = loaded_settings['sources']
		if 'choco' in user_sources:
			user_sources['chocolatey'] = user_sources.pop('choco')

		has_explicit_true = any(val is True for val in user_sources.values())
		if has_explicit_true:
			for src in self.settings['sources']:
				if src not in user_sources:
					self.settings['sources'][src] = False

	def _load_env_vars(self) -> None:
		"""Apply ``SYSTEM_UPDATE_*`` environment variable overrides."""
		if 'SYSTEM_UPDATE_SOURCES' in os.environ:
			sources_str = os.environ['SYSTEM_UPDATE_SOURCES']
			source_list = [s.strip().lower() for s in sources_str.split(',') if s.strip()]
			if 'choco' in source_list:
				source_list.append('chocolatey')
			for src in self.settings['sources']:
				self.settings['sources'][src] = src in source_list

		if 'SYSTEM_UPDATE_TIMEOUT' in os.environ:
			try:
				self.settings['performance']['timeout_seconds'] = int(
					os.environ['SYSTEM_UPDATE_TIMEOUT']
				)
			except ValueError:
				pass

		if 'SYSTEM_UPDATE_WORKERS' in os.environ:
			try:
				self.settings['performance']['max_workers'] = int(
					os.environ['SYSTEM_UPDATE_WORKERS']
				)
			except ValueError:
				pass

		if 'SYSTEM_UPDATE_EXCLUDE' in os.environ:
			exclude_str = os.environ['SYSTEM_UPDATE_EXCLUDE']
			self.settings.setdefault('exclude', [])
			self.settings['exclude'].extend(
				[e.strip() for e in exclude_str.split(',') if e.strip()]
			)

		if 'SYSTEM_UPDATE_LOG_LEVEL' in os.environ:
			self.settings['log_level'] = os.environ['SYSTEM_UPDATE_LOG_LEVEL'].upper()

		# Generic double-underscore nested overrides: SYSTEM_UPDATE_SECTION__KEY=VALUE
		prefix = 'SYSTEM_UPDATE_'
		for key, val in os.environ.items():
			if key.startswith(prefix) and '__' in key:
				path = key[len(prefix) :].lower().split('__')
				self._set_nested_env_value(self.settings, path, val)

	@staticmethod
	def _set_nested_env_value(target: Dict, path: List[str], value: str) -> None:
		"""Set a nested dict value from an env-var path, casting the scalar."""
		for key in path[:-1]:
			if key not in target:
				target[key] = {}
			target = target[key]

		final_key = path[-1]
		val_lower = value.lower()
		if val_lower in ('true', 'yes', '1'):
			target[final_key] = True
		elif val_lower in ('false', 'no', '0'):
			target[final_key] = False
		elif value.isdigit():
			target[final_key] = int(value)
		else:
			try:
				target[final_key] = float(value)
			except ValueError:
				target[final_key] = value

	@staticmethod
	def _migrate_config(loaded: Dict) -> Dict:
		"""Auto-upgrade old configs to current format."""
		version = loaded.get('version', 0)
		if version < 1:
			loaded['version'] = 1
		return loaded

	def _validate_config(self) -> None:
		"""Reset invalid configuration values to their defaults."""
		if (
			not isinstance(self.settings['cache']['duration_hours'], (int, float))
			or self.settings['cache']['duration_hours'] < 0
		):
			logging.warning('Invalid cache.duration_hours. Resetting to default (2).')
			self.settings['cache']['duration_hours'] = 2

		if (
			not isinstance(self.settings['performance']['max_workers'], int)
			or self.settings['performance']['max_workers'] < 1
		):
			logging.warning('Invalid performance.max_workers. Resetting to default (6).')
			self.settings['performance']['max_workers'] = 6

		if (
			not isinstance(self.settings['performance']['timeout_seconds'], int)
			or self.settings['performance']['timeout_seconds'] < 1
		):
			logging.warning('Invalid performance.timeout_seconds. Resetting to default (45).')
			self.settings['performance']['timeout_seconds'] = 45

		network = self.settings.setdefault('network', {})
		network['enabled'] = bool(network.get('enabled', True))
		network['cache_enabled'] = bool(network.get('cache_enabled', True))
		for key, default in (
			('cache_ttl_seconds', 3600),
			('timeout_seconds', 10),
		):
			if not isinstance(network.get(key), (int, float)) or network[key] < 1:
				logging.warning(f'Invalid network.{key}. Resetting to default ({default}).')
				network[key] = default
		if (
			not isinstance(network.get('rate_limit_seconds'), (int, float))
			or network['rate_limit_seconds'] < 0
		):
			logging.warning('Invalid network.rate_limit_seconds. Resetting to default (0.2).')
			network['rate_limit_seconds'] = 0.2

		valid_thresholds = ['low', 'medium', 'high', 'critical']
		try:
			if self.settings['security']['severity_threshold'].lower() not in valid_thresholds:
				logging.warning("Invalid security.severity_threshold. Resetting to 'medium'.")
				self.settings['security']['severity_threshold'] = 'medium'
		except (AttributeError, KeyError):
			self.settings['security']['severity_threshold'] = 'medium'

		self.settings['cache']['enabled'] = bool(self.settings['cache']['enabled'])
		if (
			not isinstance(self.settings['cache'].get('lru_max_items'), int)
			or self.settings['cache']['lru_max_items'] < 1
		):
			logging.warning('Invalid cache.lru_max_items. Resetting to default (512).')
			self.settings['cache']['lru_max_items'] = 512
		if (
			not isinstance(self.settings['cache'].get('prefetch_threshold_minutes'), int)
			or self.settings['cache']['prefetch_threshold_minutes'] < 1
		):
			logging.warning('Invalid cache.prefetch_threshold_minutes. Resetting to default (15).')
			self.settings['cache']['prefetch_threshold_minutes'] = 15
		if (
			not isinstance(self.settings['cache'].get('prune_after_days'), int)
			or self.settings['cache']['prune_after_days'] < 1
		):
			logging.warning('Invalid cache.prune_after_days. Resetting to default (14).')
			self.settings['cache']['prune_after_days'] = 14
		self.settings['cache']['incremental_enabled'] = bool(
			self.settings['cache'].get('incremental_enabled', True)
		)
		self.settings['cache']['delta_enabled'] = bool(
			self.settings['cache'].get('delta_enabled', True)
		)
		self.settings['cache']['omit_empty_fields'] = bool(
			self.settings['cache'].get('omit_empty_fields', True)
		)
		self.settings['cache']['prefetch_enabled'] = bool(
			self.settings['cache'].get('prefetch_enabled', False)
		)
		if not isinstance(self.settings['cache'].get('storage_fields'), list):
			logging.warning('Invalid cache.storage_fields. Resetting to default field list.')
			self.settings['cache']['storage_fields'] = self._get_default_settings()['cache'][
				'storage_fields'
			]
		self.settings['security']['enabled'] = bool(self.settings['security']['enabled'])

	def _merge_settings(self, base: Dict, loaded: Dict) -> None:
		"""Recursively merge ``loaded`` into ``base`` (in-place)."""
		for key, value in loaded.items():
			if key in base and isinstance(base[key], dict) and isinstance(value, dict):
				self._merge_settings(base[key], value)
			else:
				base[key] = value

	def save(self) -> None:
		"""Persist current settings to YAML (if present on disk) or JSON."""
		yaml_path = (
			self.yaml_config_file
			if self.yaml_config_file.exists()
			else (self.yml_config_file if self.yml_config_file.exists() else None)
		)

		try:
			if yaml_path:
				import yaml

				with open(yaml_path, 'w', encoding='utf-8') as f:
					yaml.dump(self.settings, f, default_flow_style=False, sort_keys=False)
			else:
				with open(self.config_file, 'w', encoding='utf-8') as f:
					json.dump(self.settings, f, indent=2, default=str)
		except ImportError:
			try:
				with open(self.config_file, 'w', encoding='utf-8') as f:
					json.dump(self.settings, f, indent=2, default=str)
			except Exception as e:
				logging.error(f'Failed to save config: {e}')
		except Exception as e:
			logging.error(f'Failed to save config: {e}')


# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════


class _DebugFormatter(logging.Formatter):
	"""Detailed logging format used by ``errors.log`` and the primary log file.

	Includes ISO timestamp (with milliseconds), level, fully-qualified logger
	name, source file:line, function, process/thread ids, and the message.
	When the record carries an exception, the traceback is appended on
	following lines so a single grep finds the full failure context.
	"""

	default_msec_format = '%s.%03d'

	def format(self, record: logging.LogRecord) -> str:
		# Render absolute (not relative) path so log lines are clickable in
		# editors and unambiguous when multiple installs share a log dir.
		try:
			location = f'{Path(record.pathname).resolve()}:{record.lineno}'
		except Exception:
			location = f'{record.pathname}:{record.lineno}'

		header = (
			f'{self.formatTime(record, self.datefmt)} | '
			f'{record.levelname:<8} | '
			f'{record.name} | '
			f'{location} | '
			f'{record.funcName}() | '
			f'pid={record.process} tid={record.thread} | '
			f'{record.getMessage()}'
		)

		# Exception info → multiline indented block so the grep-by-prefix
		# pattern still works for the header line.
		if record.exc_info:
			tb = self.formatException(record.exc_info)
			header += '\n  ' + tb.replace('\n', '\n  ')
		if record.stack_info:
			header += '\n  ' + record.stack_info.replace('\n', '\n  ')
		return header


class WarningFileHandler(logging.FileHandler):
	"""File handler that only records WARNING and above with full context.

	Writes to ``errors.log`` using :class:`_DebugFormatter` so each entry
	has timestamp, level, module, file:line, function, pid/tid, and the
	full traceback when one is available.
	"""

	def __init__(
		self, filename, mode: str = 'a', encoding: str = 'utf-8', delay: bool = False
	) -> None:
		super().__init__(filename, mode, encoding, delay)
		self.setLevel(logging.WARNING)
		self.setFormatter(_DebugFormatter(datefmt='%Y-%m-%d %H:%M:%S'))


class _SuppressExecFailureFilter(logging.Filter):
	"""Keep noisy subprocess diagnostics in the primary system log only."""

	def filter(self, record: logging.LogRecord) -> bool:
		message = record.getMessage()
		return not (
			record.name == 'system_update.utils' and message.startswith('[EXEC] Command failed')
		)


class SystemLogFileHandler(logging.FileHandler):
	"""Primary log handler that separates executions before the first record."""

	def __init__(
		self, filename, mode: str = 'a', encoding: str = 'utf-8', delay: bool = False
	) -> None:
		super().__init__(filename, mode, encoding, delay)
		self._divider_written = False

	def emit(self, record: logging.LogRecord) -> None:
		if not self._divider_written:
			self._write_execution_divider()
			self._divider_written = True
		super().emit(record)

	def _write_execution_divider(self) -> None:
		if self.stream is None:
			self.stream = self._open()

		started_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
		divider = '=' * 100
		prefix = '\n' if self.stream.tell() else ''
		self.stream.write(
			f'{prefix}{divider}\nSystem Update execution started: {started_at}\n{divider}\n'
		)
		self.flush()


def setup_logging(
	config: SystemConfig,
	debug: bool = False,
	enable_log: bool = False,
) -> None:
	"""Configure root logger: primary log file + warning-only error file.

	Args:
		config: The active :class:`SystemConfig` — its ``log_file`` and
			``config_dir`` determine where log files go.
		debug: If True, verbose logs are also echoed to stderr.
		enable_log: If True, INFO logs are written to ``system.log``.
	"""
	root_logger = logging.getLogger()

	for handler in root_logger.handlers[:]:
		root_logger.removeHandler(handler)

	file_handler = SystemLogFileHandler(config.log_file, encoding='utf-8')
	file_handler.setFormatter(_DebugFormatter(datefmt='%Y-%m-%d %H:%M:%S'))
	file_handler.setLevel(logging.DEBUG)
	root_logger.addHandler(file_handler)

	console_handler = logging.StreamHandler(sys.stderr)
	console_handler.setFormatter(logging.Formatter('%(levelname)s: %(message)s'))
	console_handler.setLevel(logging.DEBUG if debug else logging.WARNING)
	console_handler.addFilter(_SuppressExecFailureFilter())
	stream = console_handler.stream
	if hasattr(stream, 'reconfigure'):
		# Pyright sees TextIO; the runtime check above guards the call.
		stream.reconfigure(encoding='utf-8', errors='replace')  # type: ignore[union-attr]
	root_logger.addHandler(console_handler)

	error_handler = WarningFileHandler(config.config_dir / 'errors.log')
	error_handler.addFilter(_SuppressExecFailureFilter())
	root_logger.addHandler(error_handler)

	root_logger.setLevel(logging.DEBUG)
