"""Report templating — custom HTML templates, logo embedding, and branding.

Implements enhancement section 5.3 (Report Templates):
    5.3.1 — custom HTML templates
    5.3.2 — logo insertion
    5.3.3 — report branding (colors, title, company, footer)

Design: single placeholder-based template (``str.format`` with named tokens,
no Jinja dependency). The default template mirrors the built-in ``export_html``
output; users can drop a ``report.html`` file alongside their config or point
``--html-template`` at any path. Missing placeholders in user templates are
tolerated silently (unknown tokens raise, but extra whitespace/text is fine).
"""

from __future__ import annotations

import base64
import logging
import mimetypes
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

from system_update.models import AppInfo, UpdateStatus
from system_update.utils import SOURCE_ICONS, display_source

# Hex colours for HTML source chips. Mirrors Rich palette in
# ``utils._SOURCE_BADGE_STYLES`` but expressed as concrete CSS values.
_SOURCE_HEX = {
	'winget': '#0078d4',
	'chocolatey': '#80b5e3',
	'npm': '#cb3837',
	'pnpm': '#f69220',
	'pip': '#3776ab',
	'bun': '#fbf0df',
	'yarn': '#2c8ebb',
	'rust': '#dea584',
	'path': '#2e7d32',
	'registry': '#5c5c5c',
	'scoop': '#fbbd08',
	'dotnet': '#512bd4',
	'appx': '#0078d4',
	'msix': '#0078d4',
	'drivers': '#0288d1',
	'services': '#2e7d32',
	'psmodules': '#7b1fa2',
	'vsextensions': '#007acc',
}


def _source_text_color(hex_bg: str) -> str:
	"""Pick black or white text based on background luminance."""
	h = hex_bg.lstrip('#')
	if len(h) != 6:
		return '#ffffff'
	try:
		r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
	except ValueError:
		return '#ffffff'
	# Perceptual luminance — light bg → dark text.
	luma = (0.299 * r + 0.587 * g + 0.114 * b) / 255
	return '#222222' if luma > 0.6 else '#ffffff'

logger = logging.getLogger(__name__)


# ─── Branding ──────────────────────────────────────────────────────────────


@dataclass
class ReportBranding:
	"""Visual/textual branding injected into the HTML template placeholders."""

	title: str = 'System Update Report'
	subtitle: str = ''
	company_name: str = ''
	primary_color: str = '#0066cc'
	accent_color: str = '#333333'
	background_color: str = '#f5f5f5'
	footer_text: str = 'Generated by System Update CLI'
	logo_path: str = ''
	logo_data_uri: str = field(default='', repr=False)

	def ensure_logo_loaded(self) -> None:
		"""Populate ``logo_data_uri`` from ``logo_path`` if the file exists."""
		if self.logo_data_uri or not self.logo_path:
			return
		try:
			self.logo_data_uri = load_logo_data_uri(self.logo_path)
		except Exception as e:  # pragma: no cover — defensive
			logger.warning(f'Failed to embed logo {self.logo_path}: {e}')
			self.logo_data_uri = ''


def load_logo_data_uri(path: str) -> str:
	"""Read ``path`` and return a ``data:`` URI suitable for ``<img src>``."""
	p = Path(path).expanduser()
	if not p.is_file():
		return ''
	mime, _ = mimetypes.guess_type(str(p))
	mime = mime or 'image/png'
	encoded = base64.b64encode(p.read_bytes()).decode('ascii')
	return f'data:{mime};base64,{encoded}'


def resolve_branding(
	settings: Optional[Dict] = None,
	overrides: Optional[Dict] = None,
) -> ReportBranding:
	"""Merge config ``settings['report']`` with CLI ``overrides`` into branding."""
	cfg = dict((settings or {}).get('report', {}) or {})
	brand_cfg = dict(cfg.get('branding') or {})
	if 'logo_path' in cfg and 'logo_path' not in brand_cfg:
		brand_cfg['logo_path'] = cfg['logo_path']
	for k, v in (overrides or {}).items():
		if v is not None and v != '':
			brand_cfg[k] = v
	fields = {f.name for f in ReportBranding.__dataclass_fields__.values()}
	clean = {k: v for k, v in brand_cfg.items() if k in fields}
	branding = ReportBranding(**clean)
	branding.ensure_logo_loaded()
	return branding


# ─── Template ──────────────────────────────────────────────────────────────


DEFAULT_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - {scan_time}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; background: {background_color}; color: {accent_color}; }}
        header {{ display: flex; align-items: center; gap: 16px; border-bottom: 2px solid {primary_color}; padding-bottom: 12px; margin-bottom: 16px; }}
        header .logo {{ max-height: 56px; max-width: 200px; }}
        header .titles {{ flex: 1; }}
        header h1 {{ margin: 0; color: {primary_color}; }}
        header .subtitle {{ color: {accent_color}; font-size: 14px; opacity: 0.75; }}
        header .company {{ font-weight: 600; font-size: 13px; color: {primary_color}; }}
        .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 15px; margin: 20px 0; }}
        .stat {{ background: white; padding: 15px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); text-align: center; }}
        .stat-value {{ font-size: 24px; font-weight: bold; }}
        .stat-label {{ color: #666; font-size: 14px; margin-top: 5px; }}
        .up-to-date {{ color: #28a745; }}
        .update-available {{ color: #ffc107; }}
        .vulnerable {{ color: #dc3545; }}
        .unknown {{ color: #6c757d; }}
        table {{ width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        th {{ background: {primary_color}; color: white; padding: 12px; text-align: left; }}
        td {{ padding: 10px 12px; border-bottom: 1px solid #eee; }}
        tr:hover {{ background: #f8f9fa; }}
        .status {{ padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 500; }}
        .status-up-to-date {{ background: #d4edda; color: #155724; }}
        .status-update {{ background: #fff3cd; color: #856404; }}
        .status-vulnerable {{ background: #f8d7da; color: #721c24; }}
        .status-unknown {{ background: #e2e3e5; color: #383d41; }}
        .status-error {{ background: #f8d7da; color: #721c24; }}
        .footer {{ margin-top: 20px; color: #666; font-size: 12px; text-align: center; }}
        .source-chips {{ display: flex; flex-wrap: wrap; gap: 8px; margin: 10px 0 4px; }}
        .source-chip {{ display: inline-flex; align-items: center; gap: 6px; padding: 6px 12px; border-radius: 999px; font-size: 13px; font-weight: 600; box-shadow: 0 1px 2px rgba(0,0,0,0.08); border: 1px solid rgba(0,0,0,0.06); }}
        .source-chip .icon {{ font-size: 15px; line-height: 1; }}
        .source-chip .name {{ text-transform: lowercase; letter-spacing: 0.2px; }}
        .source-chip .count {{ background: rgba(255,255,255,0.85); color: #222; padding: 1px 8px; border-radius: 999px; font-weight: 700; font-size: 12px; }}
    </style>
</head>
<body>
    <header>
        {logo_html}
        <div class="titles">
            <h1>{title}</h1>
            {subtitle_html}
            {company_html}
        </div>
    </header>
    <p><strong>Generated:</strong> {scan_time}</p>
    <div class="summary">
{summary_cards}
    </div>
    <h2>Packages</h2>
    <table>
        <thead>
            <tr><th>Package</th><th>Source</th><th>Current Version</th><th>Latest Version</th><th>Status</th></tr>
        </thead>
        <tbody>
{packages_rows}
        </tbody>
    </table>
{vuln_section}
{security_summary_section}
{sources_section}
    <div class="footer"><p>{footer_text}</p></div>
</body>
</html>
"""


# ─── Rendering helpers ─────────────────────────────────────────────────────


_HTML_STATUS_CLASS = {
	UpdateStatus.UP_TO_DATE: 'status-up-to-date',
	UpdateStatus.UPDATE_AVAILABLE: 'status-update',
	UpdateStatus.SECURITY_UPDATE_AVAILABLE: 'status-update',
	UpdateStatus.VULNERABLE: 'status-vulnerable',
	UpdateStatus.UNKNOWN: 'status-unknown',
	UpdateStatus.ERROR: 'status-error',
}


def _html_escape(text: str) -> str:
	return (
		(text or '')
		.replace('&', '&amp;')
		.replace('<', '&lt;')
		.replace('>', '&gt;')
		.replace('"', '&quot;')
	)


def _summary_cards(stats: Dict) -> str:
	cards = [
		('', stats['total'], 'Total Packages'),
		('up-to-date', stats['up_to_date'], 'Up to Date'),
		('update-available', stats['update_available'], 'Updates Available'),
		('vulnerable', stats['vulnerable'], 'Vulnerable'),
		('unknown', stats['unknown'], 'Unknown'),
	]
	return '\n'.join(
		f'        <div class="stat">'
		f'<div class="stat-value {cls}">{val}</div>'
		f'<div class="stat-label">{label}</div></div>'
		for cls, val, label in cards
	)


def _packages_rows(apps: List[AppInfo]) -> str:
	rows: List[str] = []
	for app in apps:
		status_class = _HTML_STATUS_CLASS.get(app.update_status, 'status-unknown')
		status_text = (
			app.status_display.split(' ')[0]
			if ' ' in app.status_display
			else app.update_status.value
		)
		rows.append(
			f'            <tr>'
			f'<td><strong>{_html_escape(app.name)}</strong></td>'
			f'<td>{_html_escape(display_source(app.source))}</td>'
			f'<td>{_html_escape(app.version or "-")}</td>'
			f'<td>{_html_escape(app.latest_version or "-")}</td>'
			f'<td><span class="status {status_class}">{_html_escape(status_text)}</span></td>'
			f'</tr>'
		)
	return '\n'.join(rows)


def _vuln_section(apps: List[AppInfo], total_vulnerable: int) -> str:
	vuln_apps = [a for a in apps if a.security_findings]
	if not (vuln_apps or total_vulnerable > 0):
		return ''
	rows: List[str] = []
	for app in vuln_apps:
		for finding in app.security_findings:
			rows.append(
				f'            <tr>'
				f'<td><strong>{_html_escape(app.name)}</strong></td>'
				f'<td>{_html_escape(display_source(app.source))}</td>'
				f'<td>{_html_escape(app.version)}</td>'
				f'<td>{_html_escape(finding.get("cve", finding.get("cve_id", "N/A")))}</td>'
				f'<td><span class="status status-vulnerable">'
				f'{_html_escape(finding.get("severity", "UNKNOWN"))}</span></td>'
				f'</tr>'
			)
	return (
		'    <h2>🔥 Security Vulnerabilities Detected</h2>\n'
		'    <table>\n'
		'        <thead>\n'
		'            <tr><th>Package</th><th>Source</th><th>Version</th>'
		'<th>CVE</th><th>Severity</th></tr>\n'
		'        </thead>\n'
		'        <tbody>\n'
		+ '\n'.join(rows)
		+ '\n        </tbody>\n    </table>\n'
	)


def _security_summary_section(sec: Dict) -> str:
	if not (sec['critical'] or sec['high'] or sec['medium'] or sec['low']):
		return ''
	return (
		'    <h2>📈 Security Summary</h2>\n'
		'    <div class="summary">\n'
		f'        <div class="stat"><div class="stat-value">{sec["total_vulns"]}</div>'
		'<div class="stat-label">Total Vulns</div></div>\n'
		f'        <div class="stat"><div class="stat-value">{sec["packages_affected"]}</div>'
		'<div class="stat-label">Packages Affected</div></div>\n'
		f'        <div class="stat"><div class="stat-value">{sec["critical"]}</div>'
		'<div class="stat-label">Critical</div></div>\n'
		f'        <div class="stat"><div class="stat-value vulnerable">{sec["high"]}</div>'
		'<div class="stat-label">High</div></div>\n'
		f'        <div class="stat"><div class="stat-value update-available">{sec["medium"]}</div>'
		'<div class="stat-label">Medium</div></div>\n'
		f'        <div class="stat"><div class="stat-value unknown">{sec["low"]}</div>'
		'<div class="stat-label">Low</div></div>\n'
		'    </div>\n'
	)


def _sources_section(source_counts: Dict[str, int]) -> str:
	if not source_counts:
		return ''
	chips: List[str] = []
	for src, cnt in sorted(source_counts.items(), key=lambda kv: (-kv[1], kv[0])):
		label = display_source(src)
		key = label.lower()
		bg = _SOURCE_HEX.get(key, '#6c757d')
		fg = _source_text_color(bg)
		icon = SOURCE_ICONS.get(key, '📦')
		chips.append(
			f'        <span class="source-chip" '
			f'style="background:{bg};color:{fg};border-color:{bg};" '
			f'title="{_html_escape(label)}: {cnt} package(s)">'
			f'<span class="icon">{icon}</span>'
			f'<span class="name">{_html_escape(label)}</span>'
			f'<span class="count">{cnt}</span>'
			f'</span>'
		)
	return (
		'    <h2>📦 Sources</h2>\n'
		'    <div class="source-chips">\n'
		+ '\n'.join(chips)
		+ '\n    </div>\n'
	)


# ─── Public API ────────────────────────────────────────────────────────────


def load_template(template_path: Optional[str]) -> str:
	"""Return the template string from ``template_path`` or the built-in default."""
	if not template_path:
		return DEFAULT_HTML_TEMPLATE
	p = Path(template_path).expanduser()
	if not p.is_file():
		logger.warning(f'Template not found: {template_path} — using default.')
		return DEFAULT_HTML_TEMPLATE
	try:
		return p.read_text(encoding='utf-8')
	except Exception as e:
		logger.warning(f'Failed to read template {template_path}: {e} — using default.')
		return DEFAULT_HTML_TEMPLATE


def build_context(
	apps: List[AppInfo],
	branding: ReportBranding,
	scan_time: str,
) -> Dict[str, str]:
	"""Build the placeholder dict consumed by ``str.format`` rendering."""
	from system_update.export import get_export_stats, security_summary

	stats = get_export_stats(apps)
	sec = security_summary(apps)

	logo_html = (
		f'<img class="logo" src="{branding.logo_data_uri}" alt="logo">'
		if branding.logo_data_uri
		else ''
	)
	subtitle_html = (
		f'<div class="subtitle">{_html_escape(branding.subtitle)}</div>'
		if branding.subtitle
		else ''
	)
	company_html = (
		f'<div class="company">{_html_escape(branding.company_name)}</div>'
		if branding.company_name
		else ''
	)

	return {
		'title': _html_escape(branding.title),
		'scan_time': _html_escape(scan_time),
		'subtitle_html': subtitle_html,
		'company_html': company_html,
		'logo_html': logo_html,
		'footer_text': _html_escape(branding.footer_text),
		'primary_color': branding.primary_color,
		'accent_color': branding.accent_color,
		'background_color': branding.background_color,
		'summary_cards': _summary_cards(stats),
		'packages_rows': _packages_rows(apps),
		'vuln_section': _vuln_section(apps, stats['vulnerable']),
		'security_summary_section': _security_summary_section(sec),
		'sources_section': _sources_section(stats['source_counts']),
	}


class _SafeDict(dict):
	"""Dict that returns ``{key}`` for missing placeholders so unknown tokens are preserved."""

	def __missing__(self, key: str) -> str:  # pragma: no cover — trivial
		return '{' + key + '}'


def render_html(
	apps: List[AppInfo],
	branding: Optional[ReportBranding] = None,
	template_path: Optional[str] = None,
	scan_time: Optional[str] = None,
) -> str:
	"""Render the full HTML report with ``branding`` into the template text."""
	from datetime import datetime

	branding = branding or ReportBranding()
	branding.ensure_logo_loaded()
	scan_time = scan_time or datetime.now().strftime('%Y-%m-%d %H:%M:%S')
	template = load_template(template_path)
	ctx = build_context(apps, branding, scan_time)
	try:
		return template.format_map(_SafeDict(ctx))
	except Exception as e:
		logger.error(f'Template render failed ({e}); falling back to default.')
		return DEFAULT_HTML_TEMPLATE.format_map(_SafeDict(ctx))


def render_history_html(
        scans: List[Dict],
        trends: Dict,
        stale: List[Dict],
        vuln_stats: Dict,
        generated: str,
        branding,
) -> str:
    """Build a self-contained HTML history report."""

    def _esc(text) -> str:
        return (
            str(text)
            .replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;')
            .replace('"', '&quot;')
        )

    scan_rows = '\n'.join(
        f'<tr><td>{_esc(s.get("timestamp", ""))}</td>'
        f'<td>{_esc(display_source(str(s.get("source", "-"))))}</td>'
        f'<td>{s.get("package_count", 0)}</td>'
        f'<td>{s.get("update_count", 0)}</td>'
        f'<td>{s.get("vulnerability_count", 0)}</td></tr>'
        for s in scans[:50]
    )
    trend_rows = '\n'.join(
        f'<tr><td>{_esc(display_source(str(r.get("source", "-"))))}</td>'
        f'<td>{r.get("total_scans", 0)}</td>'
        f'<td>{r.get("total_packages", 0) or 0}</td>'
        f'<td>{r.get("total_updates", 0) or 0}</td></tr>'
        for r in (trends.get('source_stats') or [])
    )
    stale_rows = '\n'.join(
        f'<tr><td>{_esc(r.get("package_name", ""))}</td>'
        f'<td>{_esc(display_source(str(r.get("source", "-"))))}</td>'
        f'<td>{_esc(r.get("last_seen", ""))}</td></tr>'
        for r in stale[:100]
    )
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<title>{_esc(branding.title)} — History — {_esc(generated)}</title>
<style>
body {{ font-family: -apple-system, "Segoe UI", sans-serif; max-width: 1100px; margin: 0 auto; padding: 20px; background: {branding.background_color}; color: {branding.accent_color}; }}
h1, h2 {{ color: {branding.primary_color}; }}
table {{ width: 100%; border-collapse: collapse; background: white; box-shadow: 0 2px 4px rgba(0,0,0,0.08); margin: 12px 0 24px; border-radius: 8px; overflow: hidden; }}
th {{ background: {branding.primary_color}; color: white; padding: 10px; text-align: left; }}
td {{ padding: 8px 10px; border-bottom: 1px solid #eee; }}
.kpi {{ display: inline-block; margin-right: 18px; padding: 8px 14px; border-radius: 8px; background: white; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
.kpi b {{ color: {branding.primary_color}; }}
.footer {{ margin-top: 30px; color: #666; font-size: 12px; text-align: center; }}
</style></head><body>
<h1>📚 History Report</h1>
<p><strong>Generated:</strong> {_esc(generated)}</p>

<h2>🛡️ Vulnerabilities</h2>
<div>
  <span class="kpi"><b>{vuln_stats.get('total_vulnerabilities', 0)}</b> total</span>
  <span class="kpi"><b>{vuln_stats.get('open_vulnerabilities', 0)}</b> open</span>
  <span class="kpi"><b>{vuln_stats.get('resolved_vulnerabilities', 0)}</b> resolved</span>
  <span class="kpi"><b>{vuln_stats.get('critical_count', 0)}</b> critical</span>
  <span class="kpi"><b>{vuln_stats.get('high_count', 0)}</b> high</span>
  <span class="kpi"><b>{vuln_stats.get('packages_affected', 0)}</b> packages affected</span>
  <span class="kpi"><b>{vuln_stats.get('persistent_vulnerabilities', 0)}</b> persistent</span>
</div>

<h2>📈 Trends — last {trends.get('period_days', 30)} day(s)</h2>
<p>Unique packages tracked: <b>{trends.get('unique_packages', 0)}</b></p>
<table><thead><tr><th>Source</th><th>Scans</th><th>Packages</th><th>Updates</th></tr></thead>
<tbody>{trend_rows or '<tr><td colspan="4">No data.</td></tr>'}</tbody></table>

<h2>🕰️ Stale packages (>90d)</h2>
<table><thead><tr><th>Package</th><th>Source</th><th>Last seen</th></tr></thead>
<tbody>{stale_rows or '<tr><td colspan="3">None.</td></tr>'}</tbody></table>

<h2>📜 Recent scans</h2>
<table><thead><tr><th>Timestamp</th><th>Source</th><th>Pkgs</th><th>Updates</th><th>Vulns</th></tr></thead>
<tbody>{scan_rows or '<tr><td colspan="5">No scans recorded.</td></tr>'}</tbody></table>

<div class="footer"><p>{_esc(branding.footer_text)}</p></div>
</body></html>"""
